import type {
  AccountsData,
  BudgetsData,
  InvestmentsData,
  SpendingData,
  SubscriptionsData,
  TransactionRow,
  TransactionsData,
} from "@/lib/detail-data";
import type { DashboardData, SetupData } from "@/lib/data";

const accounts = [
  {
    id: 1,
    institutionName: "Mercury Community",
    name: "Everyday checking",
    type: "checking",
    mask: "2481",
    source: "plaid",
    balance: 8632.44,
    availableBalance: 8421.18,
    connected: true,
    lastSyncedAt: "2026-08-01T18:42:00-04:00",
  },
  {
    id: 2,
    institutionName: "Clearwater Bank",
    name: "High-yield savings",
    type: "savings",
    mask: "6012",
    source: "plaid",
    balance: 20648.72,
    availableBalance: 20648.72,
    connected: true,
    lastSyncedAt: "2026-08-01T18:42:00-04:00",
  },
  {
    id: 3,
    institutionName: "Summit Credit",
    name: "Rewards card",
    type: "credit card",
    mask: "7730",
    source: "plaid",
    balance: -1260.38,
    availableBalance: 8739.62,
    connected: true,
    lastSyncedAt: "2026-08-01T18:42:00-04:00",
  },
  {
    id: 4,
    institutionName: "Northstar Investing",
    name: "Individual brokerage",
    type: "brokerage",
    mask: "9824",
    source: "robinhood",
    balance: 42180.16,
    availableBalance: null,
    connected: true,
    lastSyncedAt: "2026-08-01T18:41:00-04:00",
  },
  {
    id: 5,
    institutionName: "Northstar Investing",
    name: "Roth IRA",
    type: "ira",
    mask: "1809",
    source: "robinhood",
    balance: 22183.06,
    availableBalance: null,
    connected: true,
    lastSyncedAt: "2026-08-01T18:41:00-04:00",
  },
];

function transaction(
  id: number,
  overrides: Partial<TransactionRow>,
): TransactionRow {
  const date = overrides.date ?? "2026-08-01";
  return {
    id,
    externalId: `demo-${id}`,
    date,
    authorizedDate: date,
    transactionAt: null,
    name: overrides.merchantName ?? "Sample transaction",
    merchantName: null,
    originalDescription: null,
    category: "OTHER",
    categoryDetailed: null,
    amount: -10,
    currencyCode: "USD",
    institutionName: "Mercury Community",
    accountName: "Everyday checking",
    accountOfficialName: "Everyday Checking",
    accountMask: "2481",
    accountType: "depository",
    accountSubtype: "checking",
    accountSource: "plaid",
    pending: false,
    paymentChannel: "in store",
    transactionCode: null,
    checkNumber: null,
    location: null,
    storeNumber: null,
    logoUrl: null,
    website: null,
    updatedAt: "2026-08-01T18:42:00-04:00",
    ...overrides,
  };
}

const transactions: TransactionRow[] = [
  transaction(1, {
    date: "2026-08-01",
    transactionAt: "2026-08-01T09:02:00-04:00",
    name: "ACME PAYROLL DIRECT DEP",
    merchantName: "Acme Payroll",
    category: "INCOME",
    categoryDetailed: "INCOME_WAGES",
    amount: 4850,
    paymentChannel: "other",
  }),
  transaction(2, {
    date: "2026-08-01",
    transactionAt: "2026-08-01T17:21:00-04:00",
    name: "WHOLE FOODS 10234",
    merchantName: "Whole Foods Market",
    category: "FOOD_AND_DRINK",
    categoryDetailed: "FOOD_AND_DRINK_GROCERIES",
    amount: -84.26,
  }),
  transaction(3, {
    date: "2026-08-01",
    name: "NORTHSTAR COFFEE",
    merchantName: "Northstar Coffee",
    category: "FOOD_AND_DRINK",
    categoryDetailed: "FOOD_AND_DRINK_COFFEE",
    amount: -6.75,
    pending: true,
  }),
  transaction(4, {
    date: "2026-07-30",
    name: "SPOTIFY USA",
    merchantName: "Spotify",
    category: "ENTERTAINMENT",
    categoryDetailed: "ENTERTAINMENT_MUSIC_AND_AUDIO",
    amount: -11.99,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
    paymentChannel: "online",
  }),
  transaction(5, {
    date: "2026-07-29",
    name: "UBER TRIP",
    merchantName: "Uber",
    category: "TRANSPORTATION",
    categoryDetailed: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
    amount: -22.4,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
    paymentChannel: "online",
  }),
  transaction(6, {
    date: "2026-07-28",
    name: "CEDAR PROPERTY CO",
    merchantName: "Cedar Property Co.",
    category: "RENT_AND_UTILITIES",
    categoryDetailed: "RENT_AND_UTILITIES_RENT",
    amount: -1780,
    paymentChannel: "online",
  }),
  transaction(7, {
    date: "2026-07-27",
    name: "TARGET 1842",
    merchantName: "Target",
    category: "GENERAL_MERCHANDISE",
    categoryDetailed: "GENERAL_MERCHANDISE_SUPERSTORES",
    amount: -126.14,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
  }),
  transaction(8, {
    date: "2026-07-26",
    name: "TREASURY INTEREST",
    merchantName: "Treasury interest",
    category: "INCOME",
    categoryDetailed: "INCOME_INTEREST_EARNED",
    amount: 18.72,
    institutionName: "Clearwater Bank",
    accountName: "High-yield savings",
    accountOfficialName: "High-Yield Savings",
    accountMask: "6012",
    accountSubtype: "savings",
    paymentChannel: "other",
  }),
  transaction(9, {
    date: "2026-07-24",
    name: "SHELL OIL 44192",
    merchantName: "Shell",
    category: "TRANSPORTATION",
    categoryDetailed: "TRANSPORTATION_GAS",
    amount: -48.12,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
  }),
  transaction(10, {
    date: "2026-07-22",
    name: "MORNINGSIDE DENTAL",
    merchantName: "Morningside Dental",
    category: "MEDICAL",
    categoryDetailed: "MEDICAL_DENTAL_CARE",
    amount: -140,
    paymentChannel: "in store",
  }),
  transaction(11, {
    date: "2026-07-20",
    name: "NETFLIX.COM",
    merchantName: "Netflix",
    category: "ENTERTAINMENT",
    categoryDetailed: "ENTERTAINMENT_TV_AND_MOVIES",
    amount: -22.99,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
    paymentChannel: "online",
  }),
  transaction(12, {
    date: "2026-07-18",
    name: "REI 184",
    merchantName: "REI",
    category: "GENERAL_MERCHANDISE",
    categoryDetailed: "GENERAL_MERCHANDISE_SPORTING_GOODS",
    amount: -89.45,
    institutionName: "Summit Credit",
    accountName: "Rewards card",
    accountOfficialName: "Rewards Credit Card",
    accountMask: "7730",
    accountType: "credit",
    accountSubtype: "credit card",
  }),
];

export const mockDashboardData: DashboardData = {
  metrics: {
    netWorth: 92384,
    netWorthChange: 8732,
    netWorthChangePercent: 10.43,
    monthlyCashFlow: 4759,
    monthlyIncome: 4850,
    monthlySpending: 91,
    investmentValue: 64363,
  },
  trend: [
    { date: "2025-09-01", value: 76620 },
    { date: "2025-10-01", value: 78140 },
    { date: "2025-11-01", value: 79780 },
    { date: "2025-12-01", value: 81250 },
    { date: "2026-01-01", value: 80390 },
    { date: "2026-02-01", value: 83240 },
    { date: "2026-03-01", value: 85110 },
    { date: "2026-04-01", value: 86980 },
    { date: "2026-05-01", value: 88420 },
    { date: "2026-06-01", value: 90170 },
    { date: "2026-07-01", value: 91330 },
    { date: "2026-08-01", value: 92384 },
  ],
  spending: [
    { category: "FOOD_AND_DRINK", value: 91.01 },
    { category: "TRANSPORTATION", value: 70.52 },
    { category: "GENERAL_MERCHANDISE", value: 215.59 },
    { category: "ENTERTAINMENT", value: 34.98 },
    { category: "MEDICAL", value: 140 },
  ],
  accounts,
  recentTransactions: transactions.slice(0, 8).map((item) => ({
    id: item.id,
    date: item.date,
    transactionAt: item.transactionAt,
    name: item.name,
    merchantName: item.merchantName,
    category: item.category,
    amount: item.amount,
    accountName: item.accountName,
    pending: item.pending,
  })),
  lastSuccessfulSync: "2026-08-01T18:42:00-04:00",
  completedSyncAt: "2026-08-01T18:42:00-04:00",
  failedSyncAt: null,
};

export const mockTransactionsData: TransactionsData = {
  transactions,
  categories: [
    "ENTERTAINMENT",
    "FOOD_AND_DRINK",
    "GENERAL_MERCHANDISE",
    "INCOME",
    "MEDICAL",
    "RENT_AND_UTILITIES",
    "TRANSPORTATION",
  ],
  accounts: ["Everyday checking", "High-yield savings", "Rewards card"],
  periodStarts: {
    mtd: "2026-08-01",
    last30Days: "2026-07-03",
    last90Days: "2026-05-04",
    ytd: "2026-01-01",
  },
  metrics: {
    income: 4850,
    spending: 91.01,
    net: 4758.99,
    pending: 6.75,
  },
};

export const mockAccountsData: AccountsData = {
  accounts,
  metrics: {
    assets: 93644.38,
    liabilities: 1260.38,
    availableCash: 29069.9,
    connected: 5,
  },
};

export const mockInvestmentsData: InvestmentsData = {
  accounts: [
    {
      id: 4,
      name: "Individual brokerage",
      officialName: "Individual Investing",
      institutionName: "Northstar Investing",
      mask: "9824",
      value: 42180.16,
      costBasis: 37192.4,
      gain: 4987.76,
      gainPercent: 13.41,
    },
    {
      id: 5,
      name: "Roth IRA",
      officialName: "Roth IRA",
      institutionName: "Northstar Investing",
      mask: "1809",
      value: 22183.06,
      costBasis: 19958.64,
      gain: 2224.42,
      gainPercent: 11.15,
    },
  ],
  history: [
    { date: "2025-09-01", value: 3450 },
    { date: "2025-10-01", value: 3860 },
    { date: "2025-11-01", value: 4210 },
    { date: "2025-12-01", value: 4580 },
    { date: "2026-01-01", value: 4090 },
    { date: "2026-02-01", value: 4880 },
    { date: "2026-03-01", value: 5210 },
    { date: "2026-04-01", value: 5680 },
    { date: "2026-05-01", value: 6040 },
    { date: "2026-06-01", value: 6480 },
    { date: "2026-07-01", value: 6810 },
    { date: "2026-08-01", value: 7212.18 },
  ],
  metrics: {
    value: 64363.22,
    costBasis: 57151.04,
    gain: 7212.18,
    gainPercent: 12.62,
    accounts: 2,
  },
};

export const mockBudgetsData: BudgetsData = {
  budgets: [
    { category: "FOOD_AND_DRINK", spent: 822, monthlyLimit: 1000, remaining: 178, percent: 82.2 },
    { category: "TRANSPORTATION", spent: 446, monthlyLimit: 650, remaining: 204, percent: 68.62 },
    { category: "GENERAL_MERCHANDISE", spent: 389, monthlyLimit: 500, remaining: 111, percent: 77.8 },
    { category: "ENTERTAINMENT", spent: 158, monthlyLimit: 200, remaining: 42, percent: 79 },
    { category: "MEDICAL", spent: 140, monthlyLimit: 400, remaining: 260, percent: 35 },
    { category: "PERSONAL_CARE", spent: 214, monthlyLimit: 350, remaining: 136, percent: 61.14 },
  ],
  metrics: {
    planned: 3100,
    spent: 2169,
    remaining: 931,
    categoriesSet: 6,
  },
};

export const mockSubscriptionsData: SubscriptionsData = {
  subscriptions: [
    {
      ruleId: null,
      streamKey: "spotify-monthly",
      merchant: "Spotify",
      category: "ENTERTAINMENT",
      averageAmount: 11.99,
      monthlyEquivalent: 11.99,
      annualized: 143.88,
      cadence: "Monthly",
      occurrences: 6,
      lastChargedAt: "2026-07-30",
      nextExpectedAt: "2026-08-30",
      confidence: "Strong match",
      source: "Automatic",
    },
    {
      ruleId: null,
      streamKey: "netflix-monthly",
      merchant: "Netflix",
      category: "ENTERTAINMENT",
      averageAmount: 22.99,
      monthlyEquivalent: 22.99,
      annualized: 275.88,
      cadence: "Monthly",
      occurrences: 6,
      lastChargedAt: "2026-07-20",
      nextExpectedAt: "2026-08-20",
      confidence: "Strong match",
      source: "Automatic",
    },
    {
      ruleId: 12,
      streamKey: "gym-monthly",
      merchant: "Harbor Fitness",
      category: "PERSONAL_CARE",
      averageAmount: 59,
      monthlyEquivalent: 59,
      annualized: 708,
      cadence: "Monthly",
      occurrences: 5,
      lastChargedAt: "2026-07-15",
      nextExpectedAt: "2026-08-15",
      confidence: "Manual",
      source: "Manual",
    },
    {
      ruleId: null,
      streamKey: "cloud-annual",
      merchant: "Cloud Storage",
      category: "GENERAL_SERVICES",
      averageAmount: 99.99,
      monthlyEquivalent: 8.33,
      annualized: 99.99,
      cadence: "Annual",
      occurrences: 2,
      lastChargedAt: "2026-06-12",
      nextExpectedAt: "2027-06-12",
      confidence: "Likely",
      source: "Automatic",
    },
  ],
  transactionChoices: transactions
    .filter((item) => item.amount < 0)
    .slice(0, 6)
    .map((item) => ({
      id: item.id,
      merchant: item.merchantName ?? item.name,
      amount: Math.abs(item.amount),
      occurredAt: item.date,
      category: item.category,
    })),
  dismissed: [],
  metrics: {
    monthlyEstimate: 102.31,
    annualEstimate: 1227.75,
    dueNext30Days: 93.98,
    detected: 4,
  },
};

const availableMonths = [
  "2026-08-01",
  "2026-07-01",
  "2026-06-01",
  "2026-05-01",
  "2026-04-01",
  "2026-03-01",
  "2026-02-01",
  "2026-01-01",
];

export function getMockSpendingData(requestedMonth?: string): SpendingData {
  const selectedMonth = availableMonths.find((month) =>
    month.startsWith(requestedMonth ?? "2026-08"),
  ) ?? availableMonths[0];
  const selectedIndex = availableMonths.indexOf(selectedMonth);
  const selectedScale = 1 + selectedIndex * 0.035;
  const monthlyBase = [
    { month: "2026-03-01", income: 4760, spending: 3920 },
    { month: "2026-04-01", income: 4850, spending: 4175 },
    { month: "2026-05-01", income: 4850, spending: 3895 },
    { month: "2026-06-01", income: 4920, spending: 4250 },
    { month: "2026-07-01", income: 4868.72, spending: 4057 },
    { month: "2026-08-01", income: 4850, spending: 91.01 },
  ].map((month) => ({ ...month, net: month.income - month.spending }));
  const categories = [
    { category: "RENT_AND_UTILITIES", value: 1780 },
    { category: "FOOD_AND_DRINK", value: 822 },
    { category: "TRANSPORTATION", value: 446 },
    { category: "GENERAL_MERCHANDISE", value: 389 },
    { category: "ENTERTAINMENT", value: 158 },
    { category: "MEDICAL", value: 140 },
  ].map((item) => ({ ...item, value: item.value * selectedScale }));
  const spending = categories.reduce((sum, item) => sum + item.value, 0);
  const income = 4868.72;

  return {
    selectedMonth,
    availableMonths,
    monthly: monthlyBase,
    categories,
    metrics: {
      income,
      spending,
      net: income - spending,
      topCategory: categories[0],
    },
  };
}

export const mockSetupData: SetupData = {
  database: "connected",
  sources: [
    {
      source: "plaid",
      status: "connected",
      label: "Plaid institutions",
      lastAttemptAt: "2026-08-01T18:42:00-04:00",
      lastSuccessAt: "2026-08-01T18:42:00-04:00",
      lastError: null,
      accounts: 3,
      connections: 3,
      institutions: ["Clearwater Bank", "Mercury Community", "Summit Credit"],
    },
    {
      source: "robinhood",
      status: "connected",
      label: "Robinhood",
      lastAttemptAt: "2026-08-01T18:41:00-04:00",
      lastSuccessAt: "2026-08-01T18:41:00-04:00",
      lastError: null,
      accounts: 2,
      connections: 1,
      institutions: ["Northstar Investing"],
    },
  ],
  totalAccounts: 5,
};
